feat: Add Hyperion Config (#6)

diff --git a/install-with-disk b/install-with-disk
--- a/install-with-disk
+++ b/install-with-disk
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
-DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 
 TARGET_HOST="${1:-}"
 TARGET_USER="${2:-paul}"
@@ -12,8 +12,8 @@ if [ "$(id -u)" -eq 0 ]; then
 fi
 
 if [[ -z "$TARGET_HOST" ]]; then
-    echo "ERROR! $(basename "${0}") requires a hostname as the first argument"
-    exit 1
+  echo "ERROR! $(basename "${0}") requires a hostname as the first argument"
+  exit 1
 fi
 
 if [ ! -e "hosts/${TARGET_HOST}/disks.nix" ]; then
@@ -24,7 +24,7 @@ fi
 # Check if the machine we're provisioning expects a keyfile to unlock a disk.
 # If it does, generate a new key, and write to a known location.
 if grep -q "data.keyfile" "hosts/${TARGET_HOST}/disks.nix"; then
-  echo -n "$(head -c32 /dev/random | base64)" > /tmp/data.keyfile
+  echo -n "$(head -c32 /dev/random | base64)" >/tmp/data.keyfile
 fi
 
 echo "WARNING! The disks in ${TARGET_HOST} are about to get wiped"
@@ -34,27 +34,20 @@ echo
 read -p "Are you sure? [y/N]" -n 1 -r
 echo
 if [[ $REPLY =~ ^[Yy]$ ]]; then
-    sudo true
+  sudo true
 
-    sudo nix run github:nix-community/disko \
-        --extra-experimental-features "nix-command flakes" \
-        --no-write-lock-file \
-        -- \
-        --mode zap_create_mount \
-        "hosts/${TARGET_HOST}/disks.nix"
+  sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko/latest -- --mode destroy,format,mount "hosts/${TARGET_HOST}/disks.nix" --yes-wipe-all-disks
 
-    sudo nixos-install --flake ".#${TARGET_HOST}"
+  sudo nixos-install --flake ".#${TARGET_HOST}"
 
-    # Rsync my nix-config to the target install
-    mkdir -p "/mnt/home/${TARGET_USER}/.dotfiles"
-    rsync -a --delete "${DIR}/.." "/mnt/home/${TARGET_USER}/.dotfiles"
+  # Rsync my nix-config to the target install
+  mkdir -p "/mnt/home/${TARGET_USER}/.dotfiles"
+  rsync -a --delete "${DIR}/.." "/mnt/home/${TARGET_USER}/.dotfiles"
 
-    # If there is a keyfile for a data disk, put copy it to the root partition and
-    # ensure the permissions are set appropriately.
-    if [[ -f "/tmp/data.keyfile" ]]; then
-      sudo cp /tmp/data.keyfile /mnt/etc/data.keyfile
-      sudo chmod 0400 /mnt/etc/data.keyfile
-    fi
+  # If there is a keyfile for a data disk, put copy it to the root partition and
+  # ensure the permissions are set appropriately.
+  if [[ -f "/tmp/data.keyfile" ]]; then
+    sudo cp /tmp/data.keyfile /mnt/etc/data.keyfile
+    sudo chmod 0400 /mnt/etc/data.keyfile
+  fi
 fi
-
-
